# Generated by Django 5.0.4 on 2024-09-13 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
