# Generated by Django 5.0.4 on 2024-09-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0003_task_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created",
        ),
    ]
